remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme 

title: "{ Andrew Raisbeck }"

tagline: A space for my work, my files, and my thoughts, etc...
description: >-
  This site contains the work, resume, and passion of Andrew Raisbeck - Nerd Extraordinaire

show_downloads: true
google_analytics: [Your Google Analytics tracking ID]

